<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!doctype html><html lang="es"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>Solicitudes · <c:out value="${comunidadActual.nombre}"/></title><link rel="stylesheet" href="/css/app-shell.css"/><link rel="stylesheet" href="/css/comunidad-visor.css?v=2"/></head>
<body><c:set var="sidebarActive" value="comunidades"/><c:set var="sidebarComunidadesEnabled" value="true"/><div class="app-shell"><jsp:include page="/WEB-INF/jsp/header.jsp"/><div class="app-main"><header class="profile-bar"><jsp:include page="/WEB-INF/jsp/notificacionesBell.jsp"/><div class="profile-card"><p class="profile-title">Mi perfil</p><p class="profile-role"><c:out value="${sessionScope.nombreUsuario}"/></p></div></header>
<main class="page-content community-view-page"><jsp:include page="/WEB-INF/jsp/comunity_events/fragments/cabeceraComunidad.jsp"/>
<c:if test="${not empty mensajeOk}"><div class="note-box community-alert"><c:out value="${mensajeOk}"/></div></c:if><c:if test="${not empty mensajeError}"><div class="error-box community-alert"><c:out value="${mensajeError}"/></div></c:if>
<section class="viewer-panel"><header class="viewer-panel-header"><div><h2>Solicitudes de acceso</h2><p>Gestiona las peticiones para formar parte de la comunidad.</p></div></header>
<c:choose><c:when test="${visor.publica}"><div class="privacy-state"><span class="fact-icon">◎</span><strong>Esta comunidad es pública</strong><p>No se requieren solicitudes para unirse.</p></div></c:when><c:when test="${not visor.puedeGestionar}"><div class="privacy-state"><strong>Comunidad privada</strong><p>Solo los administradores pueden consultar y resolver las solicitudes pendientes.</p></div></c:when><c:when test="${empty visor.solicitudes}"><div class="empty-state"><strong>No hay solicitudes pendientes</strong><p>Las nuevas peticiones aparecerán aquí.</p></div></c:when><c:otherwise><div class="request-grid"><c:forEach var="solicitud" items="${visor.solicitudes}"><article class="request-card"><div class="member-cell"><span class="member-avatar"><c:choose><c:when test="${not empty solicitud.fotoUrl}"><img src="<c:out value='${solicitud.fotoUrl}'/>" alt=""/></c:when><c:otherwise>♙</c:otherwise></c:choose></span><span class="member-copy"><strong><c:out value="${solicitud.nombreUsuario}"/></strong><small>Solicitud enviada el <c:out value="${solicitud.fechaSolicitud}"/></small></span></div><div class="request-actions"><form action="/comunidades/${comunidadActual.id}/solicitudes/${solicitud.solicitudId}/aceptar" method="post"><button class="button-primary" type="submit">Aceptar</button></form><form action="/comunidades/${comunidadActual.id}/solicitudes/${solicitud.solicitudId}/rechazar" method="post"><button class="button-secondary danger-action" type="submit">Rechazar</button></form></div></article></c:forEach></div></c:otherwise></c:choose>
</section></main></div></div></body></html>
